name: helpdesk_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  dropdown_search: ^6.0.2
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_form_builder: ^10.2.0
  flutter_riverpod: ^3.1.0
  flutter_secure_storage: ^10.0.0
  flutter_summernote: ^1.1.1
  flutter_svg: ^2.2.3
  flutter_html: ^3.0.0-beta.2
  html_editor_enhanced: ^2.5.1
  http: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/favicon/
# Splash Screen Configuration
flutter_native_splash:
  image: assets/images/logo_with_bg.jpg
  
  # Warna bg
  color: "#FFFFFF"
  android_gravity: fill
  ios_content_mode: scaleAspectFit
  android_screen_orientation: portrait
  
  # Platform support
  android: true
  ios: true
  web: false
  
  android_12:
    image: assets/images/logo_with_bg.jpg
    color: "#FFFFFF"

  fullscreen: true

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/favicon/android-chrome-512x512.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/favicon/android-chrome-512x512.png"
  remove_alpha_ios: true